server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: PostService
          uri: lb://POSTSERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
        - id: UserService
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - name = AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
