server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
  
  # -----------------------------
  # PostService route
spring.cloud.gateway.routes[0].id=PostService
spring.cloud.gateway.routes[0].uri=lb://POSTSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/posts/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2
  
  # -----------------------------
  # UserService route
spring.cloud.gateway.routes[1].id=UserService
spring.cloud.gateway.routes[1].uri=lb://USERSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/users/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=2
